"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var lab4_1 = require("./lab4");
var Dog = lab4_1.Animals.Dog;
var Cat = lab4_1.Animals.Cat;
var Animal = lab4_1.Animals.Animal;
var Town = lab4_1.Animals.Town;
var AnimalType = lab4_1.Animals.AnimalType;
var Owner = lab4_1.Animals.Owner;
var AnimalStorage = lab4_1.Animals.AnimalStorage;
var dog = new Dog('Собака-кусака', 'Укусь', Town.KEMEROVO);
var dog1 = new Dog('Собака-кусака-2', 'Укусь-2', Town.MOSCOW);
var owner = new Owner(new Date(), 'Дмитрий', 'Дмитриев');
dog.owner = owner;
var cat = new Cat('Мяука-кусюка', 'Мяу-тяу', Town.KEMEROVO);
var cat1 = new Cat('Мяука-кусюка-2', 'Мяу-тяу-2', Town.SAMARA);
cat1.owner = owner;
var fish = new Animal('Жабродышаший рыб', 'Барабулик', Town.KEMEROVO, AnimalType.FISH);
var hamster = new Animal('Крутящий генератор', 'Хомячилла', Town.MOSCOW, AnimalType.HAMSTER);
var parrot = new Animal('Пукни в пакетик', 'Приветик', Town.SAMARA, AnimalType.PARROT);
var mouse = new Animal('Настало время захватить мир', 'Брэйн', Town.RIGA, AnimalType.MOUSE);
var rat = new Animal('Для лидера нет никаких оправданий', 'Сплинтер', Town.NEW_YORK, AnimalType.RAT);
var monkey = new Animal('Продавала кирпичи', 'Чичичи', Town.NEW_YORK, AnimalType.MONKEY);
var catStorage = new AnimalStorage();
catStorage.save(cat);
catStorage.save(cat1);
var dogStorage = new AnimalStorage();
dogStorage.save(dog);
dogStorage.save(dog1);
var animalStorage = new AnimalStorage();
animalStorage.save(dog);
animalStorage.save(cat);
animalStorage.save(fish);
animalStorage.save(hamster);
animalStorage.save(parrot);
animalStorage.save(mouse);
animalStorage.save(rat);
animalStorage.save(monkey);
console.log(catStorage.getAll());
console.log(dogStorage.getAll());
console.log(animalStorage.getAll());
